apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: dev
spec:
  containers:
  - name: maven
    image: maven:3.6.3-jdk-8
    command: ['cat']
    tty: true
    env:
    - name: JAVA_HOME
      value: /opt/java/openjdk
    - name: MAVEN_HOME
      value: /usr/share/maven
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2
  - name: jnlp
    image: jenkins/inbound-agent:jdk17
    args: ['-jnlpUrl', 'http://jenkins:8080/jnlpJars/agent.jar', '-secret', '${JENKINS_SECRET}', '-name', '${JENKINS_NAME}', '-workDir', '/home/jenkins']
    env:
    - name: JENKINS_URL
      value: http://jenkins:8080
    - name: JENKINS_SECRET
      value: f40b8727d77e95b5e6e91c7760bc7d26862dce5f675a461d095052c1e77e7fe7
    - name: JENKINS_NAME
      value: jenkins-agent
    volumeMounts:
    - name: maven-cache
      mountPath: /root/.m2
  volumes:
  - name: maven-cache
    emptyDir: {}