
pipeline {
  agent {
      kubernetes {         
          defaultContainer 'jnlp' 
          yamlFile '.devops/jenkins-agent.yml'
      }
  }
  environment {
        APP_NAME="distributed-lock"
  }
  stages {
    stage('BUILD') {
      steps {
            container('maven') {
                sh 'mvn clean package -U -e -Dmaven.test.skip=true'
            }
        }
    }
    stage('TEST') {
      steps {
            container('maven') {
                sh 'mvn test -e'
            }
        }
        post {
          always {
            //archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            junit testResults: 'target/surefire-reports/*.xml', allowEmptyResults: true
          }
        }
    }
  }
}
